<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="DTOs\" />
      <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\SharedLibrary\SharedLibrary.csproj" />
      <ProjectReference Include="..\Quiz.Domain\Quiz.Domain.csproj" />
      <ProjectReference Include="..\Quiz.Infrastructure\Quiz.Infrastructure.csproj" />
    </ItemGroup>

</Project>
